### ISSUE TITLE
能否新增设置，可设置抽屉面板位置

### ISSUE THREAD

**Issue by cobish** [wolf3c/vTab#1]
能否新增设置，比如我可能想放在右侧。

我是双屏，浏览器放右侧的大屏，左滑鼠标就移动到副屏，没触发到面板的展示。

**Comment by wolf3c** [comment]
收到，我最近评估一下，有两个顾虑：
1. 如果两边都有副屏，可能还是解决不了问题；
2. 右边展开sidebar使用起来可能没有左边那么习惯性；

**Comment by wolf3c** [comment]
@cobish 尝试增加了右侧展示的设置，Chrome 商店审核需要一天左右，如果你使用的GitHub release 版本，可以直接下载最新版本 .crx 文件：https://github.com/wolf3c/vTab/releases

**Comment by wolf3c** [comment]
@cobish 希望听到你反馈使用几天后的感受，thx

**Comment by cobish** [comment]
给力，点赞👍🏻
