### ISSUE TITLE
Bug 反馈：电脑暗色主题，网页是浅色（例如 github），vTab 看不清

### ISSUE THREAD

**Issue by Allenxuxu** [wolf3c/vTab#3]
电脑主题和浏览器主题都是暗色，打开浅色系网站（例如 github），无法看清，因为 vTab 字体为白色，背景也是浅色。

**Comment by wolf3c** [comment]
感谢反馈，这确是之前没有注意，最近更新优化

**Comment by wolf3c** [comment]
@Allenxuxu 已经增加暗色模式，Chrome 商店审核需要一天左右，如果你使用的GitHub release 版本，可以直接下载 2.10版本 .crx 文件：https://github.com/wolf3c/vTab/releases

**Comment by Allenxuxu** [comment]
> @Allenxuxu 已经增加暗色模式，Chrome 商店审核需要一天左右，如果你使用的GitHub release 版本，可以直接下载 2.10版本 .crx 文件：https://github.com/wolf3c/vTab/releases

非常感谢支持暗色，速度太快了👍
