### ISSUE TITLE
增强型安全浏览功能不信任此扩展程序

### ISSUE THREAD

**Issue by crazypeace** [wolf3c/vTab#4]
为什么会有这样的提醒?
![image](https://github.com/wolf3c/vTab/assets/665889/297aa5c8-0faf-45c8-b99f-3086e8d4dd7c)

**Comment by crazypeace** [comment]
我安装 Link Map 没有这样的提醒

https://chromewebstore.google.com/detail/link-map/jappgmhllahigjolfpgbjdfhciabdnde

**Comment by wolf3c** [comment]
@crazypeace 根据我的研究，可能是因为我是一个新的 chrome extension 开发人员，还没有被列入 Chrome Web Store 开发人员计划政策，所以都会弹出不受信任的提醒。

详情见：https://pcservices.com.my/2021/06/06/google-chrome-%E7%8E%B0%E5%9C%A8%E8%AD%A6%E5%91%8A%E7%94%A8%E6%88%B7%E6%9D%A5%E8%87%AA%E4%B8%8D%E5%8F%97%E4%BF%A1%E4%BB%BB%E5%BC%80%E5%8F%91%E8%80%85%E7%9A%84%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F/

**Comment by wolf3c** [comment]
> 为什么会有这样的提醒? ![image](https://private-user-images.githubusercontent.com/665889/345274280-297aa5c8-0faf-45c8-b99f-3086e8d4dd7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTE1OTIsIm5iZiI6MTcxOTk5MTI5MiwicGF0aCI6Ii82NjU4ODkvMzQ1Mjc0MjgwLTI5N2FhNWM4LTBmYWYtNDVjOC1iOTlmLTMwODZlOGQ0ZGQ3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNzIxMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjlhYjUxMWZjZGI4NjBjY2RlMDU1MjAxMTU4ZmExOTQwZjc0YTI1MDc2NzM0NDMxZWE1MGZhMzFlNDczMTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UwMOU-RnkGhhkuASNbKTVn80z6Wxv_tF-JrcRQs26-4)

借用你的提问，我已经在 readme 增加了说明：

<img width="872" alt="image" src="https://github.com/wolf3c/vTab/assets/9410030/8044a7b8-c1a7-4a3a-9ac7-4e2518350fbd">
