### ISSUE TITLE
我设置的是右边，但每次开页面都会在左边闪一下

### ISSUE THREAD

**Issue by zhl111** [wolf3c/vTab#5]
感觉拖慢了浏览的速度呢？

**Comment by wolf3c** [comment]
@zhl111 确实是获取配置有延迟导致的，🤔 我看看怎么可以优化

**Comment by wolf3c** [comment]
@zhl111 已修复，如果你是用的Chrome extension store版本，审核需要1天，请等待升级。如果你是用GitHub release版本，见 https://github.com/wolf3c/vTab/releases/tag/3.2

**Comment by wolf3c** [comment]
fixed. Chrome extension store 已经发布
